spring.application.name=TaskManagement

# This is for the Application Login
spring.security.user.name=Ace
spring.security.user.password=munezero

spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=Munezero

# Hibernate settings to automatically create tables based on your @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
